import {getWrongAnswer} from '../../../../helpers/string';

const column1 = [
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'4976',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7642',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4796',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'4926',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'2769',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7426',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'2794',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4276',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //10

    {
        question:'7964',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'2769',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9724',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'2974',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4726',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4697',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9764',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //20

    {
        question:'6947',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9246',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6472',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7496',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7249',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'7624',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    // 30

    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'6279',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'2496',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'6794',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'2746',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4792',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'9624',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7249',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },

    //40

    {
        question:'2967',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7264',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'6249',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9672',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6247',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'7924',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4692',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    }

    //50
]

const column2 = [
    {
        question:'0813',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'1058',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'1850',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3185',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1053',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'3805',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5180',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },

    //10

    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'1038',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'0581',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'1385',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'0351',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5380',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'8105',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3058',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },

    //20

    {
        question:'8013',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'5831',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'8013',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3150',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5381',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'5801',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'0318',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3501',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'0385',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5031',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //30
    {
        question:'3815',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'0318',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8305',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'0835',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5301',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5183',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8315',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'0315',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //40

    {
        question:'1853',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8051',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3185',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1530',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3581',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3058',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'3105',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //50


]

const column3 = [
    {
        question:'5274',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'2145',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'5741',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'2715',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'1742',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'4521',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'7254',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
]

const column4 = [
    {
        question:'3628',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2386',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2603',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0362',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'8362',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6023',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0826',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
]

const column5 = [
    {
        question:'9471',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'9374',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'9714',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'3914',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'1379',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'9134',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'3749',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7319',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
]
const angka = [ 
  ...column1,
  ...column2,
  ...column3,
  ...column4,
  ...column5
]

export default angka