import {getWrongAnswer} from '../../../../helpers/string';

const column1 = [
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'4976',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7642',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4796',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'4926',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'2769',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7426',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'2794',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4276',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //10

    {
        question:'7964',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'2769',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9724',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'2974',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4726',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4697',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9764',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //20

    {
        question:'6947',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9246',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6472',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7496',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6924',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7249',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'7624',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    // 30

    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'6279',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'2496',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'6794',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'2746',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'4792',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'9624',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7249',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },

    //40

    {
        question:'2967',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'7264',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'6249',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'9672',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'6247',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'7924',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'4692',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'7269',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    }

    //50
]

const column2 = [
    {
        question:'0813',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'1058',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'1850',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3185',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1053',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'3805',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5180',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },

    //10

    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'1038',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'0581',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8053',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'1385',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'0351',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5380',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'8105',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3058',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },

    //20

    {
        question:'8013',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'5831',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'8013',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3150',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5381',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'5801',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'0318',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'3501',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'0385',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5031',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //30
    {
        question:'3815',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'0318',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8305',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'0835',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'5301',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'5183',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'8315',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'0315',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //40

    {
        question:'1853',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'8051',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3185',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1530',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3581',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'3058',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'3105',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //50


]

const column3 = [
    {
        question:'5274',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'2145',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'5741',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'2715',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'1742',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'4521',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'7254',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //10

    {
        question:'7124',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'4257',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'2457',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'7251',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'5214',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'4572',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'5412',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'7541',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'5217',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'7421',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //20

    {
        question:'1542',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'1745',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'1425',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'2754',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'7125',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'2741',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'1275',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'7451',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'2754',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4721',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //30

    {
        question:'2471',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'7541',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'5172',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'5421',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'7145',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'5421',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'7214',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'7521',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'1475',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'4257',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },

    //40

    {
        question:'7512',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'1725',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'1547',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'5421',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'4751',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'7254',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'2751',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'5417',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'7254',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'4215',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },

    //50
]

const column4 = [
    {
        question:'3628',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2386',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2603',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0362',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'8362',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6023',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0826',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },

    //10
    {
        question:'8032',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'3602',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6238',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3206',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'3682',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2036',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'0863',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },

    //20

    {
        question:'6830',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'8206',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'6302',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'8326',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2308',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'0682',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //30

    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'0863',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'8063',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'3862',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6820',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0638',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'6028',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3602',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6823',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'3082',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //40

    {
        question:'2608',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'2306',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'2086',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'3286',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'8302',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'2836',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'3062',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0382',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //50
]

const column5 = [
    {
        question:'9471',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'9374',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'9714',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'3914',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'1379',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'9134',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'3749',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7319',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //10

    {
        question:'3197',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'7143',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'1743',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'3149',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4197',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7431',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'4791',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3479',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4193',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'3719',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //20

    {
        question:'3491',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9314',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9473',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7349',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'1349',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4793',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7194',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },

    //30

    {
        question:'1739',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'3479',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4931',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3974',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3197',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'3419',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9734',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'7143',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },

    //40

    {
        question:'4137',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'1974',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'4379',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'1394',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9371',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'7419',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //50
]

const column6 = [
    {
        question:'9672',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2974',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'7946',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6729',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'7649',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7942',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'2694',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4769',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },

    //10

    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'7926',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'9467',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'7264',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4269',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'6794',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2946',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },

    //20

    {
        question:'6972',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'4627',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'6972',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2749',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4267',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'4697',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'9278',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2497',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'9264',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4927',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //30

    {
        question:'2674',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'9276',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6294',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'9624',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4297',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4762',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6274',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'9274',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //40

    {
        question:'7642',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6947',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7429',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2467',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2946',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'2794',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //50
]
const angka = [ 
  ...column1,
  ...column2,
  ...column3,
  ...column4,
  ...column5
]

export default angka