import {getWrongAnswer} from '../../../../helpers/string';

const column1 = [ 
    {
        question:'BNTH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:11
    },
    {
        question:'ZBHT',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:11
    },
    {
        question:'BNTH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:11
    },
    {
        question:'HTZN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:11
    },
    {
        question:'ZHBT',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:11
    },
    {
        question:'ZBNT',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:11
    },
    {
        question:'NHTB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:11
    },
    {
        question:'HZNT',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:11
    },
    {
        question:'NHBZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:11
    },
    {
        question:'ZNHT',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:11
    },

    //10

    {
        question:'HBTZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'NHTB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'BHNZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'NBHZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'ZHNT',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },
    {
        question:'ZTBH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'TBNZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'BHTZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'HNTB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'NHTZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },

    //20

    {
        question:'TBZH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'HNTB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'BNZT',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HTBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'TZHN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },
    {
        question:'TBNZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HZBT',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'TBNZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HNZB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'HTNZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },

    // 30

    {
        question:'BNZH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'TNHB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'BNZH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'NZBT',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'BNZH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'THBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'NHZT',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },
    {
        question:'ZHBN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'BTNZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HNZB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },

    //40

    {
        question:'NBTH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'HNTZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },
    {
        question:'TNZB',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'BTHN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    },
    {
        question:'TBZN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HTBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:11
    },
    {
        question:'TNZH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:11
    },
    {
        question:'HBNZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:11
    },
    {
        question:'ZTBN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:11
    },
    {
        question:'HNTB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:11
    }
]

const column2 = [
    {
        question:'JPVC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'CJVH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'VJHP',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'PVCJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'VPHJ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CVPH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'VJHC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'CPJH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'HVPJ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CJVP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },

    //10

    {
        question:'PJHC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'VJCP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'PJHC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'JHPV',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'PJHC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'VCPH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'JCHV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'HCPJ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'PVJH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CJHP',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },

    //20

    {
        question:'PJVC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'HPCV',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'PJVC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'CVHJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'HCPV',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'HPJV',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'JCVP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'CHJV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'JCPH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'HJCV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },

    //30
    {
        question:'CPVH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'JCPV',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'PCJH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'JPCH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'HCJV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'HVPC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'VPJH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'PCVH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'CJVP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'JCVH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },

    //40

    {
        question:'VPHC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'CJVP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:12
    },
    {
        question:'VJVH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CVPH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'VHCJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },
    {
        question:'VPJH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CHPV',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:12
    },
    {
        question:'VPJH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:12
    },
    {
        question:'CJHP',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:12
    },
    {
        question:'CVJH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:12
    },

    //50


]

const column3 = [
    {
        question:'KJDW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'WJQD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'JQWK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'WJQD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'KDWQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'JDQK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'QDWJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'WKJQ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'DJKW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'WJQD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },

    //10

    {
        question:'DJQW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'WJKD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'JWKD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'DJKQ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'KJQW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'WKDJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'KWQJ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'DKWQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'KJQD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'DWJQ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },

    //20

    {
        question:'QKWJ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'QDWK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'QWJK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'JDKW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'DQJK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'JDWQ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'QJDK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'DWKQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'JDKW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'WDJQ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },

    //30

    {
        question:'JWDQ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'DKWQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'KQDJ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'KWJQ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'DQWK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'KWJQ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'DJQW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:13
    },
    {
        question:'DKJQ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'QWDK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'WJKD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },

    //40

    {
        question:'DKQJ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'QDJK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'QKWD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'KWJQ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },
    {
        question:'WDKQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'DJKW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'JDKQ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:13
    },
    {
        question:'KWQD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:13
    },
    {
        question:'DJKW',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:13
    },
    {
        question:'WJQK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:13
    },

    //50
]

const column4 = [
    {
        question:'WLXR',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'XWRL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'XLFW',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'LFRX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'FWLX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'WRLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'RWLX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'LFXW',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'WRLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'FRXL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },

    //10
    {
        question:'RFWX',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'WLFX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'LXWR',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'LFRX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'WXFL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'LFRX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'WRXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'WLRX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'XFWL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'FRLW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },

    //20

    {
        question:'LRWF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'FRXW',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'RXFL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'FRXW',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'LWFX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'RWXL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'XWFR',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'FLRX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'WRLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'FRXW',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },

    //30

    {
        question:'WRXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'FRLW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'RFLW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'WRLX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'LRXF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'FLWR',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'LFXR',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'WLFX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'LRXW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'WFRX',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },

    //40

    {
        question:'XLFR',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'XWFL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'XFRL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:14
    },
    {
        question:'RWLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'WXRL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'RWFX',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },
    {
        question:'XRWL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:14
    },
    {
        question:'WFLX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:14
    },
    {
        question:'RWLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:14
    },
    {
        question:'FWRX',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:14
    },

    //50
]

const column5 = [
    {
        question:'MSYG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'MFYS',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'MYGS',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'GFSY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'FMGS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'GFYM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'MGFS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'FYSM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'GFSY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'YFGM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },

    //10

    {
        question:'FGMY',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'YGSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'GYSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'FGSM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'SGMY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'YSFG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'SYMG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'FSYM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'SGMF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'FYGM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },

    //20

    {
        question:'FSMG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'MFGS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'MSYF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'SYGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'YFSM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'FGSY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'GFSM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'SYMF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'FGSY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'YGMS',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },

    //30

    {
        question:'GYFM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'FSYM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'SMFG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'SYGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'FMYS',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'SYGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'FGMY',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'FSGM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'MYFS',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'YGSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },

    //40

    {
        question:'SGFY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'YGMF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'GMYS',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'YGMF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'SFYM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:15
    },
    {
        question:'GFMS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:15
    },
    {
        question:'MFYG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },
    {
        question:'YSGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:15
    },
    {
        question:'FGSY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:15
    },
    {
        question:'YGMF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:15
    },

    //50
]

const column6 = [
    {
        question:'BTHN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'NBHZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'HBZT',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'THNB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'HTZB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NHTZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'HBZN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'NTBZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'ZHTB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NBHT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },

    //10

    {
        question:'TBZN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'HBNT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'TBZN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'BZTH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'TBZN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'HNTZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'HNZH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'ZNTB',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'THBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NBZT',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },

    //20

    {
        question:'TBHN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'ZTNH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'TBHN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'NHZB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'ZNTH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'ZTBH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'BNHT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'NZBH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'BNTZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'ZBNH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },

    //30

    {
        question:'NTHZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'BNHT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'TNBZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'BTNZ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'ZNBH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'ZHTN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'HTBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'TNHZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'NBHT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'BNHZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },

    //40

    {
        question:'HTZN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'NBHT',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
          soalId:16
    },
    {
        question:'TBZH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NHTZ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'HZNB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },
    {
        question:'HTBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NZTH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
          soalId:16
    },
    {
        question:'HTBZ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
          soalId:16
    },
    {
        question:'NBZT',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
          soalId:16
    },
    {
        question:'NHBZ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
          soalId:16
    },

    //50
]

const column7 = [
    {
        question:'CJHP',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'PVCJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'JVHC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PCJH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'CHPV',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'CJVH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PHCJ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'CJVH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PVHJ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'PCVH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },

    //10

    {
        question:'PJCH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'VPCJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'JPVH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'VJPH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'HPVC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'HCJP',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'CJVH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'JPCH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'PVCJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'VPCH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },

    //20

    {
        question:'VJCP',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'PVCH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'CVHJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'JCPV',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'CJHV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PCJH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'CHHP',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'PJVH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'HCJV',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PVCJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },

    //30

    {
        question:'JVHP',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'CVPJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'JVHP',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'VHJC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'VJHP',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'CPJH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'HPJV',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'JCVH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'PVHJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'JVCP',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },

    //40

    {
        question:'HJPC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'JVCP',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'PCHV',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'HPJC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'HJVC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:17
    },
    {
        question:'VPCJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:17
    },
    {
        question:'PHVC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:17
    },
    {
        question:'VPJH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },
    {
        question:'HVPC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:17
    },
    {
        question:'5183',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:17
    },

    //50
]

const column8 = [
    {
        question:'JDKQ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'KJQD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'KDWJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'DWQK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'WJDK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'JQDW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'QJDK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'DWKJ',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'JQDW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'WQKD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },

    //10

    {
        question:'QWJK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'JDWK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'DKJQ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'DWQK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'JKWD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'DWQK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'JQKW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'JDQK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'KWJD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'WQDJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },

    //20

    {
        question:'DQJW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'WQKJ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'QKWD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'WQKJ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'DJWK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'QJKD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'KJWQ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'WDQK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'JQDW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'WQKJ',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },

    //30

    {
        question:'JQKW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'WQDJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'QWDJ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'JQDK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'DQKW',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'WDJQ',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'DWKQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'JDWK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'DQKJ',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'JWQK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },

    //40

    {
        question:'KDWQ',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'KJWD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'KWQD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:18
    },
    {
        question:'QJDW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'JKQD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'QJWK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },
    {
        question:'KQJD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:18
    },
    {
        question:'JWDK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:18
    },
    {
        question:'QJDW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:18
    },
    {
        question:'WJQK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:18
    },

    //50
]

const column9 = [
    {
        question:'LXFW',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'LRFX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'LFWX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'WRXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'RLWX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'WRFL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'LWRX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'RFXL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'WRXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'FRWL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },

    //10

    {
        question:'RWLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'FWXR',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'WFXR',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'RWXL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'XWLF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'FXRW',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'XFLW',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'RXFL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'XWLR',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'RFWL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },

    //20

    {
        question:'RXLW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'LRWX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'LXFR',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'XFWL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'FRXL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'RWXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'WRXL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'XFLR',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'RWXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'FWLX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },

    //30

    {
        question:'WFRL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'RXFL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'XLRW',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'XFWL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'RLFX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'XFWL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'RWLF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'RXWL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'LFRX',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'FWXR',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },

    //40

    {
        question:'XWRF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'FWLR',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'WLFX',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'FWLR',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'XRFL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
         soalId:19
    },
    {
        question:'WRLX',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
         soalId:19
    },
    {
        question:'LRFW',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },
    {
        question:'FXWL',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
         soalId:19
    },
    {
        question:'RWXF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
         soalId:19
    },
    {
        question:'FWLR',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
         soalId:19
    },

    //50
]

const column10 = [
    {
        question:'GSMY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'YSFM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'SFYG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'YSFM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'GMYF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'SMFG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'FMYS',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'YGSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'MSGY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'YSFM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },

    //10

    {
        question:'SYMF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'MGYF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'GFMS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'GYSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'MFYG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'GYSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'MSFY',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'MGSF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'FYMG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'YSGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },

    //20

    {
        question:'FGYS',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'FMYG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'FYSG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'SMGY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'MFSG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'SMYF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'FSMG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'MYGF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'SMGY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'YMSF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },

    //30

    {
        question:'MSFY',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },
    {
        question:'YSGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'SYGM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'MSGF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'GSFY',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'YGMS',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'GYFS',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'MGYF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'GSFM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'MYSF',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
           soalId:20
    },

    //40

    {
        question:'MGFS',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'FMSG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'FGYM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'GYSF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },
    {
        question:'YMGF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'MSGY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'SMGF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
           soalId:20
    },
    {
        question:'GYFM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
           soalId:20
    },
    {
        question:'MSGY',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
           soalId:20
    },
    {
        question:'YSFG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
           soalId:20
    },

    //50
]

const huruf = [
    ...column1,
 ...column2 ,
 ...column3 ,
//  ...column4 ,
//  ...column5 ,
//  ...column6 ,
//  ...column7 ,
//  ...column8 ,
//  ...column9 ,
//  ...column10 ,
]

export default huruf