import {getWrongAnswer} from '../../../../helpers/string';

const column1 = [
    {
        question:'ACDB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'EABD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'ACDB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BDEC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EBAD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'EACD',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'CBDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BECD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'CBAE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'ECBD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //10

    {
        question:'BADE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'CBDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ABCE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'CABE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'EBCD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EDAB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ABDE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'CBDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //20

    {
        question:'DAEB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ACED',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DEBC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BEAD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCEA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'BDCE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    // 30

    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'DCBA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'CEAD',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'DBAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'CBED',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EBAC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'ADCE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCEA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },

    //40

    {
        question:'CADB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BCDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'DCEA',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ADBC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'DAEC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DCEB',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'BACE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'EDAC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    }

    //50
]

const column2 = [
    {
        question:'CAHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FCHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'HCGA',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'AHFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'HAGC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FHAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HCGF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'FACG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GHAC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },

    //10

    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'HCFA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'CGAH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'HFAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'CFGH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GFAC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'AHCG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCGA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },

    //20

    {
        question:'ACHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'GAFH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'ACHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FHGC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GFAH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'GACH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'CFHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FGCH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'CFAG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GCFH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //30
    {
        question:'FAHG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'CFHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'AFCG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'CAFG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GFCH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GHAF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'AFHG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'CFHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //40

    {
        question:'HAGF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'ACGH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FHAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HGFC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FGAH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCGA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'FHCG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //50


]

const column3 = [
    {
        question:'KIGL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'IHLK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'KGLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'IGHK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HGLI',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'LKIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //10

    {
        question:'GIHL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'LIKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'ILKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'GIKH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KIHL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LKGI',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'KLHI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GKLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KIHG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'GLIH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //20

    {
        question:'HKLI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'HGLK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'HLIK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'IGKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'GHIK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'IGLH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'HIGK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'GLKH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'IGKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LGIH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //30

    {
        question:'ILGH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'GKLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KHGI',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GHLK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GIHL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'GKIH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HLGK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'LIKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },

    //40

    {
        question:'GKHI',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HGIK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HKLG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LGKH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'IGKH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KLHG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },

    //50
]

const column4 = [
    {
        question:'3628',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2386',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2603',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0362',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'8362',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6023',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0826',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },

    //10
    {
        question:'8032',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'3602',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6238',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3206',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'3682',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2036',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'0863',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },

    //20

    {
        question:'6830',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'8206',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'6302',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'8326',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'2308',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'0682',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0823',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //30

    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'0863',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'8063',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'3862',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'6820',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'0638',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'6028',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'3602',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'6823',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'3082',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //40

    {
        question:'2608',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'2306',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'2086',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'3286',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'8302',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'2836',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'3062',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'0382',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //50
]

const column5 = [
    {
        question:'9471',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'9374',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'9714',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'3914',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'1379',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'9134',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'3749',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7319',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //10

    {
        question:'3197',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'7143',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'1743',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'3149',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4197',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7431',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'4791',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3479',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4193',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'3719',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //20

    {
        question:'3491',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9314',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9473',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7349',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'1349',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4793',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7194',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },

    //30

    {
        question:'1739',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'3479',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4931',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3974',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3197',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'3419',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9734',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'7143',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },

    //40

    {
        question:'4137',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'1974',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'4379',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'1394',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'9371',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'7419',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'3147',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'7193',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //50
]

const column6 = [
    {
        question:'9672',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2974',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'7946',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6729',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'7649',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7942',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'2694',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4769',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },

    //10

    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'7926',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'9467',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6942',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'7264',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'9247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4269',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'6794',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2946',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },

    //20

    {
        question:'6972',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'4627',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'6972',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2749',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4267',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'4697',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'9278',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'2497',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'9264',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4927',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //30

    {
        question:'2674',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'9276',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6294',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'9624',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'4297',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'4762',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'6274',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'9274',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //40

    {
        question:'7642',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'2976',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'6947',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2764',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7429',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2467',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'7694',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'2946',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'2794',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //50
]

const column7 = [
    {
        question:'3058',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'0153',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8305',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'3581',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8503',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8150',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'8315',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //10

    {
        question:'8035',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'1830',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'0815',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'1085',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'5813',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'5308',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'0835',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'1835',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //20

    {
        question:'1038',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'8135',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'3150',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'0381',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'3051',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8305',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'3158',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'8015',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'5301',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },

    //30

    {
        question:'0158',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'3180',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'0158',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'1503',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'0158',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'3805',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'1853',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'5801',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'0315',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'8150',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },

    //40

    {
        question:'0138',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'5083',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'0138',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'8351',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'5803',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'5013',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'1830',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'8513',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'1805',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'5183',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //50
]

const column8 = [
    {
        question:'2751',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'5217',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'5742',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'7415',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'4275',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'2174',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'1275',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'7452',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'2174',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'4157',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },

    //10

    {
        question:'1425',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'2745',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'7521',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'7415',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'2547',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'7415',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'2154',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'2715',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'5427',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'4172',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },

    //20

    {
        question:'7124',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'4152',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'1547',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'4152',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'7245',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'1257',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'5241',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'4715',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'2174',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'2152',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //30

    {
        question:'2154',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'4172',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'1472',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'2175',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'7154',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'4721',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'7451',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'2745',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'7152',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'2415',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //40

    {
        question:'5741',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'5247',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'5417',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'1274',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'2517',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'1245',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'5127',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'2475',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'1274',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'4215',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //50
]

const column9 = [
    {
        question:'6203',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'6802',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'6032',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'8632',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'3806',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'6382',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'8026',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'3820',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'0836',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //10

    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'0328',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'3028',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'8326',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'2360',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'0283',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'2063',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'8206',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'2368',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'8036',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //20

    {
        question:'8263',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'6832',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'6208',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'2036',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'0826',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'8320',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'3826',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'2068',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'8320',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'0362',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },

    //30

    {
        question:'3086',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'8206',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'2683',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'2036',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'8602',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'2036',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'8360',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'8236',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'0328',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },

    //40

    {
        question:'2380',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'0368',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'3602',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'0368',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'2806',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'3862',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'6803',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'0236',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'8320',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'0368',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //50
]

const column10 = [
    {
        question:'1497',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'7439',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'4371',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'7439',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'1973',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'4931',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'3974',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'7143',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'9417',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'7439',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //10

    {
        question:'4793',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'9173',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'1394',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'1743',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'9371',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'1743',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'9437',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'9143',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'3791',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'7419',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },

    //20

    {
        question:'3174',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'3971',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'3741',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'4917',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'9341',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'4973',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'3491',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'9713',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'4917',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'7943',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //30

    {
        question:'9437',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'7419',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'4719',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'9413',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'1437',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'7194',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'1734',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'9173',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'1439',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'9743',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //40

    {
        question:'9134',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'3941',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'3179',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'1743',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'7913',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'9417',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'4913',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'1739',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'9417',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'7431',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },

    //50
]

const symbol = [
    ...column1,
 ...column2 ,
 ...column3 ,
 ...column4 ,
 ...column5 ,
 ...column6 ,
 ...column7 ,
 ...column8 ,
 ...column9 ,
 ...column10 ,
]

export default symbol