import {getWrongAnswer} from '../../../../helpers/string';

const column1 = [
    {
        question:'ACDB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'EABD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'ACDB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BDEC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EBAD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'EACD',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'CBDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BECD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'CBAE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'ECBD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //10

    {
        question:'BADE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'CBDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ABCE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'CABE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'EBCD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EDAB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ABDE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'CBDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    //20

    {
        question:'DAEB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ACED',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DEBC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BEAD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DACE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCEA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'BDCE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },

    // 30

    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'DCBA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'CEAD',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'DBAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'CBED',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'EBAC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'ADCE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCEA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },

    //40

    {
        question:'CADB',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'BCDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'DCEA',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'ADBC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    },
    {
        question:'DAEC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:1
    },
    {
        question:'DCEB',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:1
    },
    {
        question:'BACE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:1
    },
    {
        question:'EDAC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:1
    },
    {
        question:'BCDA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:1
    }

    //50
]

const column2 = [
    {
        question:'CAHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FCHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'HCGA',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'AHFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'HAGC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FHAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HCGF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'FACG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GHAC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },

    //10

    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'HCFA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'CGAH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'ACGF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'HFAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'CFGH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GFAC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'AHCG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCGA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },

    //20

    {
        question:'ACHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'GAFH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'ACHF',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FHGC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GFAH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'GACH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'CFHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'FGCH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'CFAG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GCFH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //30
    {
        question:'FAHG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'CFHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'AFCG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'CAFG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'GFCH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'GHAF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'AFHG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'CFHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //40

    {
        question:'HAGF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'FCHA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:2
    },
    {
        question:'ACGH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FHAG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HGFC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FGAH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:2
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:2
    },
    {
        question:'FCGA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:2
    },
    {
        question:'FHCG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:2
    },

    //50


]

const column3 = [
    {
        question:'KIGL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'IHLK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'KGLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'IGHK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HGLI',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'LKIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHG',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //10

    {
        question:'GIHL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'LIKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'ILKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'GIKH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KIHL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LKGI',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'KLHI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GKLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KIHG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'GLIH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //20

    {
        question:'HKLI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'HGLK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'HLIK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'IGKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'GHIK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'IGLH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'HIGK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'GLKH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'IGKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LGIH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },

    //30

    {
        question:'ILGH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'GKLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KHGI',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GHLK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'GIHL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:3
    },
    {
        question:'GKIH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HLGK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'LIKG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },

    //40

    {
        question:'GKHI',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HGIK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'HKLG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'KLIH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },
    {
        question:'LGKH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'IGKH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:3
    },
    {
        question:'KLHG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:3
    },
    {
        question:'GIKL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:3
    },
    {
        question:'LIHK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:3
    },

    //50
]

const column4 = [
    {
        question:'CMDN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'DCNM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'DMLC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'MLND',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'LCMD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'CNML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'NCMD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'MLDC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'CNML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'LNDM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },

    //10
    {
        question:'NLDC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'CMLD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'MDCN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'MLND',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'CDLM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'MLND',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'CNDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'CMND',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'DLCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'LNMC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },

    //20

    {
        question:'MNCL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'LMDC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'NDLM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'LNDC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'MCLD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'NCDM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'DCLN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'LMND',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'CNML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'LNDC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //30

    {
        question:'CNDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'LNMC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'NLMC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'CNMD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'MNDL',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'LMCN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'MLDN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'CMLD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'MNDC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'CLND',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //40

    {
        question:'DMLN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'DCLM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'DLNM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:4
    },
    {
        question:'NCML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'CDNM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'MCLD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },
    {
        question:'DNCM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:4
    },
    {
        question:'CLMD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:4
    },
    {
        question:'NCML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:4
    },
    {
        question:'LCMD',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:4
    },

    //50
]

const column5 = [
    {
        question:'CMNK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'CONM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'CNKM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'KOMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'OCKM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'KONC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'CKOM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'ONMC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'KOMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'NOKC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //10

    {
        question:'OKCN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'NKMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'KNMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'OKMC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'MKCN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'NMOK',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'MNCK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'OMNC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'MKCO',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'ONKC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //20

    {
        question:'OMCK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'COKM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'CMNO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'MNKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'NOMC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'OKMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'KOMC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'MNCO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'OKMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'NKCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },

    //30

    {
        question:'KNOC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'OMNC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'MCOK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'MNKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'OCNM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'MNKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'OKCN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'OMKC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'CNOM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'NKMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },

    //40

    {
        question:'MKON',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'NKCO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'KCNM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'NKCO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'MONC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:5
    },
    {
        question:'KOCM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:5
    },
    {
        question:'CONK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },
    {
        question:'NMKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:5
    },
    {
        question:'OKMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:5
    },
    {
        question:'NKCO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:5
    },

    //50
]

const column6 = [
    {
        question:'ADBC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'CABE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'BAED',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'DBCA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'BDEA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CBDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'BAEC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'CDAE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'EBDA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CABD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },

    //10

    {
        question:'DAEC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'BACD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'DAEC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'AEDB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'DAEC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'BCDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'ACEB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'ECDA',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'DBAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CAED',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },

    //20

    {
        question:'DABC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'EDCB',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'DABC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'CBEA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'ECDB',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'EDAB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'ACBD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'CEAB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'ACDE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'EACB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //30

    {
        question:'CDBE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'ACBD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'DCAE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'ADCE',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'ECAB',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'EBDC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'DCBE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'CABD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'ACBE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //40

    {
        question:'BDEC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'CABD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:6
    },
    {
        question:'DAEB',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CBDE',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'BECA',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CEDB',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:6
    },
    {
        question:'BDAE',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:6
    },
    {
        question:'CAED',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:6
    },
    {
        question:'CBAE',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:6
    },

    //50
]

const column7 = [
    {
        question:'FCGA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'AHFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'CHGF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AFCG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'FGAH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'FCHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AGCF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'FCHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AHGC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'AFHG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //10

    {
        question:'ACFG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'HAFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'CAHG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'HCAG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'GAHF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'GHCA',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'FCHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'CAFG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'AHFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'HAFG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //20

    {
        question:'HCFA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'AHFG',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'FHGC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'CFAH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'FCGH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AFCG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'HFGA',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'ACHG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'GFCH',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AHFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },

    //30

    {
        question:'CHGA',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'FHAC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'CHGA',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'HGCF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'CHGA',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'FACG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'CAGF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'GACH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'CFHG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'AHGC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },

    //40

    {
        question:'CHFA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'GCAF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'CHFA',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'AFGH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'GACF',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:7
    },
    {
        question:'GCHF',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:7
    },
    {
        question:'HAFC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:7
    },
    {
        question:'AGHF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },
    {
        question:'HACG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:7
    },
    {
        question:'GHAF',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:7
    },

    //50
]

const column8 = [
    {
        question:'IGKH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'KIHG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'KGLI',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'GIHK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'LIGK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'IHGL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'HIGK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'GLKI',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'IHGL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'LHKG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },

    //10

    {
        question:'HLIK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'IGLK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'GKIH',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'GLHK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'IKLG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'GLHK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'IHKL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'IGHK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'KLIG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'LHGI',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },

    //20

    {
        question:'GHIL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'LHKI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'HKLG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'LHKI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'GILK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'HIKG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'KILH',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'LGHK',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'IHGL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'LHKI',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //30

    {
        question:'IHKL',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'LHGI',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'HLGI',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'IHGK',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'GHKL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'LGIH',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'GLKH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'IGLK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'GHKI',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'ILHK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //40

    {
        question:'KGLH',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'KILG',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'KLHG',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:8
    },
    {
        question:'HIGL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'IKHG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'HILK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },
    {
        question:'KHIG',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:8
    },
    {
        question:'ILGK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:8
    },
    {
        question:'HIGL',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:8
    },
    {
        question:'LIHK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:8
    },

    //50
]

const column9 = [
    {
        question:'MDLC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'MNLD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'MLCD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'CNDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'NMCD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'CNLM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'MCND',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'NLDM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'CNDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'LNCM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //10

    {
        question:'NCML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'LCDN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'CLDN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'NCDM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'DCML',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'LDMC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'DLMC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'NDLM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'DCMN',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'NLCM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //20

    {
        question:'NDMC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'MNCD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'MDLN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'DLCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'LNDM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'NCDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'CNDM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'DLMN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'NCDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'LCMD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },

    //30

    {
        question:'CLNM',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'NDLM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'DMNC',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'DLCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'NMLD',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'DLCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'NCML',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'NDCM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'MLND',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'LCDN',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },

    //40

    {
        question:'DCNL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'LCMN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'CMLD',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'LCMN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'DNLM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:9
    },
    {
        question:'CNMD',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:9
    },
    {
        question:'MNLC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },
    {
        question:'LDCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:9
    },
    {
        question:'NCDL',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:9
    },
    {
        question:'LCMN',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:9
    },

    //50
]

const column10 = [
    {
        question:'KMCN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'NMOC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'MONK',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'NMOC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'KCNO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'MCOK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'OCNM',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'NKMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'CMKN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'NMOC',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //10

    {
        question:'NMCO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'CKNO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'KOCM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'KNMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'CONK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'KNMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'CMON',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'CKMO',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'ONCK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'NMKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },

    //20

    {
        question:'OKNM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'OCNK',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'ONMK',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'MCKN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'COMN',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'MCNO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'OMCK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'CNKO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'MCKN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'NCMO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //30

    {
        question:'CMON',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },
    {
        question:'NMKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'MNKC',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'CMKO',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'KMON',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'NKCM',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'KNOM',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'CKNO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'KMOC',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'CNMO',
        correctAnswer:'a',
        wrongAnswer:getWrongAnswer('a'),
        soalId:10
    },

    //40

    {
        question:'CKOM',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'OCMK',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'OKNC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'KNMO',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },
    {
        question:'NCKO',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'CMKN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'MCKO',
        correctAnswer:'d',
        wrongAnswer:getWrongAnswer('d'),
        soalId:10
    },
    {
        question:'KNOC',
        correctAnswer:'b',
        wrongAnswer:getWrongAnswer('b'),
        soalId:10
    },
    {
        question:'CMKN',
        correctAnswer:'e',
        wrongAnswer:getWrongAnswer('e'),
        soalId:10
    },
    {
        question:'NMOK',
        correctAnswer:'c',
        wrongAnswer:getWrongAnswer('c'),
        soalId:10
    },

    //50
]

const symbol = [
    ...column1,
 ...column2 ,
 ...column3 ,
 ...column4 ,
 ...column5 ,
 ...column6 ,
 ...column7 ,
 ...column8 ,
 ...column9 ,
 ...column10 ,
]

export default symbol