const column1 = [
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:1
    },
    {
        question:'4976',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:1
    },
    {
        question:'9267',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:1
    },
    {
        question:'7642',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:1
    },
    {
        question:'4796',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:1
    },
    {
        question:'4926',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:1
    },
    {
        question:'2769',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:1
    },
    {
        question:'7426',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:1
    },
    {
        question:'2794',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:1
    },
    {
        question:'4276',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:1
    }
]

const column2 = [
    {
        question:'0813',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:2
    },
    {
        question:'3015',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:2
    },
    {
        question:'1058',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:2
    },
    {
        question:'8130',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:2
    },
    {
        question:'1850',
        correctAnswer:'a',
        wrongAnswer:'bdce',
        soalId:2
    },
    {
        question:'3185',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:2
    },
    {
        question:'1053',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:2
    },
    {
        question:'3805',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:2
    },
    {
        question:'5180',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:2
    },
    {
        question:'3018',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:2
    },
]

const column3 = [
    {
        question:'5274',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:3
    },
    {
        question:'2145',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:3
    },
    {
        question:'5741',
        correctAnswer:'a',
        wrongAnswer:'bdce',
        soalId:3
    },
    {
        question:'2715',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:3
    },
    {
        question:'1742',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:3
    },
    {
        question:'4521',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:3
    },
    {
        question:'7254',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:3
    },
    {
        question:'4217',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:3
    },
]

const column4 = [
    {
        question:'3628',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:4
    },
    {
        question:'2386',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:4
    },
    {
        question:'2603',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:4
    },
    {
        question:'6082',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:4
    },
    {
        question:'0362',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:4
    },
    {
        question:'8362',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:4
    },
    {
        question:'6023',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:4
    },
    {
        question:'3860',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:4
    },
    {
        question:'0826',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:4
    },
]

const column5 = [
    {
        question:'9471',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:5
    },
    {
        question:'9374',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:5
    },
    {
        question:'9714',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:5
    },
    {
        question:'3914',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:5
    },
    {
        question:'1379',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:5
    },
    {
        question:'9134',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:5
    },
    {
        question:'3749',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:5
    },
    {
        question:'1347',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:5
    },
    {
        question:'7319',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:5
    },
]
const angka = [ 
  ...column1,
  ...column2,
  ...column3,
  ...column4,
  ...column5
]

export default angka