const column1 = [
    {
        question:'9,2,6,7',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:1
    },
    {
        question:'4,9,7,6',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:1
    },
    {
        question:'9,2,6,7',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:1
    },
    {
        question:'7,6,4,2',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:1
    },
    {
        question:'4,7,9,6',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:1
    },
    {
        question:'4,9,2,6',
        correctAnswer:'b',
        wrongAnswer:'a,c,d,e',
        soalId:1
    },
    {
        question:'2,7,6,9',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:1
    },
    {
        question:'7,4,2,6',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:1
    },
    {
        question:'2,7,9,4',
        correctAnswer:'d',
        wrongAnswer:'a,b,c,e',
        soalId:1
    },
    {
        question:'4,2,7,6',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:1
    }
]

const column2 = [
    {
        question:'0,8,1,3',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:2
    },
    {
        question:'4,9,7,6',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:2
    },
    {
        question:'9,2,6,7',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:2
    },
    {
        question:'7,6,4,2',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:2
    },
    {
        question:'4,7,9,6',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:2
    },
    {
        question:'4,9,2,6',
        correctAnswer:'b',
        wrongAnswer:'a,c,d,e',
        soalId:2
    },
    {
        question:'2,7,6,9',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:2
    },
    {
        question:'7,4,2,6',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:2
    },
    {
        question:'2,7,9,4',
        correctAnswer:'d',
        wrongAnswer:'a,b,c,e',
        soalId:2
    },
    {
        question:'4,2,7,6',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:w
    }
]
const angka = [ 
  ...column1,
  ...column2
]

export default angka