const data = [ 
    {
        question:'B,N,T,H',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:11
    },
    {
        question:'Z,B,H,T',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:11
    },
    {
        question:'B,N,T,H',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:11
    },
    {
        question:'H,T,Z,N',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:11
    },
    {
        question:'Z,H,B,T',
        correctAnswer:'c',
        wrongAnswer:'a,b,d,e',
        soalId:11
    },
    {
        question:'Z,B,N,T',
        correctAnswer:'b',
        wrongAnswer:'a,c,d,e',
        soalId:11
    },
    {
        question:'N,H,T,B',
        correctAnswer:'e',
        wrongAnswer:'a,b,c,d',
        soalId:11
    },
    {
        question:'H,Z,N,T',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:11
    },
    {
        question:'N,H,B,Z',
        correctAnswer:'d',
        wrongAnswer:'a,b,c,e',
        soalId:11
    },
    {
        question:'Z,N,H,T',
        correctAnswer:'a',
        wrongAnswer:'b,c,d,e',
        soalId:11
    }
]

export default data