const data = [ 
    {
        question:'BNTH',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:11
    },
    {
        question:'ZBHT',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:11
    },
    {
        question:'BNTH',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:11
    },
    {
        question:'HTZN',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:11
    },
    {
        question:'ZHBT',
        correctAnswer:'c',
        wrongAnswer:'abde',
        soalId:11
    },
    {
        question:'ZBNT',
        correctAnswer:'b',
        wrongAnswer:'acde',
        soalId:11
    },
    {
        question:'NHTB',
        correctAnswer:'e',
        wrongAnswer:'abcd',
        soalId:11
    },
    {
        question:'HZNT',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:11
    },
    {
        question:'NHBZ',
        correctAnswer:'d',
        wrongAnswer:'abce',
        soalId:11
    },
    {
        question:'ZNHT',
        correctAnswer:'a',
        wrongAnswer:'bcde',
        soalId:11
    }
]

export default data