import { NextPage } from "next";
import Head from "next/head";
import AuthLayout from "@components/layouts/AuthLayout";
import { useEffect } from "react";
import { useForm } from 'react-hook-form'
import { useSession, signIn } from 'next-auth/react'
import type { SignInResponse } from 'next-auth/react'
import { useRouter } from 'next/router'

type TLogin = {
    username: string
    password: string
}

const Signin: NextPage = () => {
    const { data, status } = useSession()
    const router = useRouter()
    const { handleSubmit, register, setError, clearErrors, formState: { errors } } = useForm<TLogin>()

    const onSubmit = (data: TLogin): void => {
        clearErrors('username')
        signIn('credentials', {
            username: data.username,
            password: data.password,
            redirect: false

        }).then((resp: SignInResponse | undefined) => {

            if (resp?.error) {
                setError('username', { message: resp?.error })
            }
        })


    }

    useEffect(() => {

        if (status === 'authenticated') {
            if (data?.user.type === 'ADMIN') {

                router.push('/dashboard')
            }
            else {
                router.push('/exam')
            }
        }
    }, [status])



    return (
        <AuthLayout>
            <Head>
                <title>BAEKS - Psikotest</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='flex flex-col justify-center items-center min-h-screen w-full bg-slate-800 text-white'>
                <div className='mb-12 w-2/6 text-center flex flex-col space-y-2'>
                    <h1 className='text-4xl font-bold tracking-wider'>Selamat datang</h1>
                    <h2 className="text-sm font-light text-white opacity-50">Silahkan masukan username dan password untuk masuk</h2>
                </div>



                <form className='flex flex-col justify-center items-center w-1/3 space-y-6 bg-slate-600 p-12 rounded' onSubmit={handleSubmit(onSubmit)}>
                    {
                        errors?.username?.message && <div className='mb-12 w-4/6 text-center text-sm text-red-500'>{errors?.username.message}</div>
                    }
                    <div className='flex flex-row justify-between items-center w-full'>
                        <label htmlFor="username" className='w-1/3 mr-2 text-sm font-bold'>Username</label>
                        <input
                            {...register('username')}
                            type="text"
                            id="username"
                            placeholder='Enter your username'
                            className='border text-black border-gray-400 p-4 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
                        />
                    </div>
                    <div className='flex flex-row justify-between items-center w-full'>
                        <label htmlFor="password" className='w-1/3 mr-2 text-sm font-bold'>Password</label>
                        <input
                            {...register('password')}
                            type="password"
                            id="password"
                            placeholder='Please enter your password'
                            className='border text-black border-gray-400 p-4 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
                        />
                    </div>
                    <div className='w-full'>
                        <button className='bg-red-400 hover:bg-red-500 text-white font-bold p-4 rounded focus:outline-none focus:shadow-outline w-full text-sm'>Masuk</button>
                    </div>

                </form>

            </main>
        </AuthLayout>
    )
}

export default Signin