import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'

const Home: NextPage = (data) => {
  console.log(data)
  return (
    <div className='bg-white'>
      <Head>
        <title>BAEKS - Psikotest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col justify-center items-center min-h-screen w-full'>
        <div className='mb-12'>
          <h1 className='text-4xl font-bold tracking-wider'>BAEKS Psikotest</h1>
        </div>
        <form className='flex flex-col justify-center items-center w-1/3 space-y-4 bg-purple-200 p-12'>
          <div className='flex flex-row justify-between w-full'>
            <label htmlFor="no_registrasi" className='w-1/3 mr-2'>No</label>
            <input
              type="text"
              name="no_registrasi"
              id="no_registrasi"
              placeholder='Registration number'
              className='border border-gray-400 p-2 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
            />
          </div>
          <div className='flex flex-row justify-between w-full'>
            <label htmlFor="name" className='w-1/3 mr-2'>Nama</label>
            <input
              type="text"
              name="name"
              id="name"
              placeholder='Nama Lengkap'
              className='border border-gray-400 p-2 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
            />
          </div>
          <div className='flex flex-row justify-between w-full'>
            <label htmlFor="test_date" className='w-1/3 mr-2'>Tanggal Tes</label>
            <input
              type="date"
              name="test_date"
              id="test_date"
              placeholder='tanggal tes'

              className='border border-gray-400 p-2 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
            />
          </div>
          <div className='flex flex-row justify-between w-full'>
            <label htmlFor="purpose" className='w-1/3 mr-2'>Tujuan</label>
            <input
              type="text"
              name="purpose"
              id="purpose"
              placeholder='Tujuan tes'
              className='border border-gray-400 p-2 rounded text-sm focus:outline focus:outline-1 focus:outline-offset-2 focus:outline-gray-600 w-2/3'
            />
          </div>
          <div className='w-full'>
            <button className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full' >Submit</button>
          </div>
        </form>
      </main>

    </div>
  )
}


export const getStaticProps: GetStaticProps = async () => {
  const prisma = new PrismaClient()
  const data = prisma.user.findMany()
  return {
    props: {
      data: JSON.parse(JSON.stringify(data))
    }
  }
}

export default Home
